name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    env:
      REDIS_HOST: 'redis'

    runs-on: ubuntu-latest
    services:
      redis:
        image: redis

    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.0", "3.1", ruby-head]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true # 'bundle install' and cache gems
        ruby-version: ${{ matrix.ruby }}
    - name: Run tests
      run: bundle exec rake
